sudo: false

language: cpp

matrix:
  include :
    - os: linux
      compiler: gcc-4.9
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['g++-4.9', 'cmake', 'cmake-data', 'zlib1g-dev', 'libbz2-dev', 'libboost-dev', 'python', 'python-nose', 'python-jinja2', 'python-pip']
      install: export CXX="g++-4.9" CC="gcc-4.9"

before_script:
# - sudo apt-get install git g++ build-essential zlib1g-dev libbz2-dev libboost-all-dev
# - sudo apt-get install software-properties-common
# - sudo add-apt-repository -y ppa:george-edison55/precise-backports
# - sudo apt-get update
# - sudo apt-get install cmake cmake-data
 - git clone https://github.com/seqan/seqan.git seqan
 - git clone https://github.com/martinjvickers/alfsc.git

script:
 - cd alfsc
 - cmake ../alfsc -DCMAKE_MODULE_PATH=../seqan/util/cmake -DSEQAN_INCLUDE_PATH=../seqan/include -DCMAKE_CXX_FLAGS=-std=c++14 -DCMAKE_BUILD_TYPE=Release
 - make
