sudo: required

before_script:
 - sudo apt-get install git g++ build-essential zlib1g-dev libbz2-dev libboost-all-dev
 - sudo apt-get install software-properties-common
 - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
 - sudo apt-get update
 - sudo apt-get install cmake
 - git clone https://github.com/seqan/seqan.git seqan
 - git clone https://github.com/martinjvickers/alfsc.git

script:
 - cd alfsc
 - cmake ../alfsc -DCMAKE_MODULE_PATH=../seqan/util/cmake -DSEQAN_INCLUDE_PATH=../seqan/include -DCMAKE_CXX_FLAGS=-std=c++14 -DCMAKE_BUILD_TYPE=Release
 - make
