sudo: required

before_script:
 - sudo apt-get install git g++ build-essential cmake zlib1g-dev libbz2-dev libboost-all-dev
 - git clone https://github.com/seqan/seqan.git seqan
 - git clone https://github.com/martinjvickers/alfsc.git

script:
 - cd alfsc
 - cmake ../alfsc -DCMAKE_MODULE_PATH=../seqan/util/cmake -DSEQAN_INCLUDE_PATH=../seqan/include -DCMAKE_CXX_FLAGS=-std=c++14 -DCMAKE_BUILD_TYPE=Release
 - make
